# Generated by Django 5.1.3 on 2024-11-20 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobus', '0004_viaje_precio_alter_ruta_distancia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasajero',
            name='usuario',
        ),
        migrations.AddField(
            model_name='pasajero',
            name='nombre',
            field=models.CharField(default='Ninguno', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boleto',
            name='pasajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gobus.pasajero'),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='documento_identidad',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
