# Generated by Django 5.1.3 on 2024-11-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobus', '0004_viaje_precio_alter_ruta_distancia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasajero',
            name='usuario',
        ),
        migrations.AddField(
            model_name='conductor',
            name='apellido',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conductor',
            name='documento_identidad',
            field=models.CharField(default=4234234, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conductor',
            name='email',
            field=models.EmailField(default=' ', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conductor',
            name='fecha_nacimiento',
            field=models.DateField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasajero',
            name='apellido',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasajero',
            name='email',
            field=models.EmailField(default=' ', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasajero',
            name='fecha_nacimiento',
            field=models.DateField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasajero',
            name='nombre',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasajero',
            name='telefono',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
    ]
