# Generated by Django 5.1.3 on 2024-11-20 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobus', '0005_remove_pasajero_usuario_pasajero_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='pasajero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gobus.pasajero'),
        ),
    ]
