# Generated by Django 5.1.3 on 2024-11-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobus', '0006_alter_boleto_pasajero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='precio',
            field=models.CharField(max_length=10),
        ),
    ]
